### ISSUE TITLE
run-as alternatives?

### ISSUE THREAD

**Issue by jakewalter8213901** [freddierice/trident#6]
@freddierice Just read your article @ [https://www.redtile.io/security/galaxy/](url). In para Attack Vector you have said
#The most **common** target for this attack is /system/bin/run-as (similar to the su command in linux).

I wanted to know run-as alternatives and compiled **getcap** for android to find out which files have setcap permissions or CAP_SETUID capability but get stuck because libcap is missing. tried wpa_supplicant,  superumount, logcat; none of them have CAP_SETUID/permissions.

So do you know any alternatives of run-as?? Please:) 😞 😥

**Comment by droidvoider** [comment]
Try trident on my repo it should get you what you want now. I did a quick hack to use new dirtycow when replacing files but to still use freddie's dirtycow_memcpy to write memory since it was never broken.
The result is something that works on Note 5, no lag, no errors.. Gets root 100% of the time now.
